### ISSUE TITLE
Create github actions for versioned releases

### ISSUE THREAD

**Issue by KenEucker** [kaimallea/node-imgur#108]
@kaimallea this is a ticket I wanted to create based on what you said in #106, 

> Add developer tooling like commitizen and husky to enforce commits to follow conventional commit messaging, so that semantic versioning and releases can be automated via Github actions.

If you haven't created any GitHub actions for this automated work previously, I'd love to take on that task and learn how to do this.

**Comment by kaimallea** [comment]
I've done this work before, but am happy to get out of the way and let you dig in and learn. The combination of Commitizen, husky, and semantic-release are the tools I've worked with previously to enforce conventions and have hands-off deploys.

**Comment by KenEucker** [comment]
@kaimallea if you've already done that work then I say go for it. I'd be happy to learn just by reading your code and seeing it in action.
