### ISSUE TITLE
Add an issue template for guiding new issue submissions

### ISSUE THREAD

**Issue by KenEucker** [kaimallea/node-imgur#119]
@kaimallea what do you think about adding an issue template? I have been going through the old issues and some of them are just a couple of words. I think that adding an issue template would help with the quality of error submissions making them easier to address and also easier to close out.

Also, what do you think about creating a discussion for this repository? That would allow us to pin a discussion about features and roadmap. That could also be one way to allow people to contact via code of conduct issues. You'll see that we didn't fill out that part in the code of conduct: https://github.com/kaimallea/node-imgur/blob/develop/CODE_OF_CONDUCT.md (line 67).

**Comment by KenEucker** [comment]
Also, I feel that we should prune all issues older than 2 years that haven't been updated.

**Comment by kaimallea** [comment]
yes, yes, and yes. I love it, great suggestions. I've added bug and feature templates, and enabled discussions.

**Comment by KenEucker** [comment]
@kaimallea  Awesome! 

Here's a good list for examples of issue templates, I will probably pull from one of these and pair it down:
https://github.com/devspace/awesome-github-templates

I will also work on a contributing.md file. I like the exhaustiveness of atoms contributing guidelines:
https://github.com/atom/atom/blob/master/CONTRIBUTING.md

Or something less involved, like this one: 
https://github.com/github/docs/blob/main/CONTRIBUTING.md

And then I will submit a PR with these two additions.

**Comment by kaimallea** [comment]
Perfect, thank you!

**Comment by kaimallea** [comment]
this is done; feel free to send PR(s) with any tweaks/updates
