### ISSUE TITLE
Next versioned release from v0.3.2

### ISSUE THREAD

**Issue by KenEucker** [kaimallea/node-imgur#124]
@kaimallea the current state of the `develop` branch feels like a really great update to me. What were you thinking would be the next release? 0.3.3? If so, can we plan for a release this week?

I'm excited to use the npm package once again in my project, if we can get the current state of `develop` out as 0.3.3 that would be awesome. If you were thinking you'd rather wait for a larger release, I'm curious what you would want to add before pushing the next version?

Finally, I know that there are a few bug fixes that have made their way to the `main` branch. So at the very least, it seems we need something to be 0.3.3 if we hold on to the rest of what we have right now.

**Comment by kaimallea** [comment]
I will probably release it tonight or tomorrow. It will definitely bump to v1.0.0 bc of a few breaking changes in `develop`. A changelog will be generated

**Comment by kaimallea** [comment]
🎉  shipped
