### ISSUE TITLE
dns and http2 dependency?

### ISSUE THREAD

**Issue by fsalliau** [kaimallea/node-imgur#163]
Hi,

I tried to install and run imgur@2..0.0.next-3 in a Vue project.
I got the following message:

![image](https://user-images.githubusercontent.com/9927768/114035767-b501e180-987f-11eb-8212-99ab24d5d543.png)

When installing the dns and http2 dependencies, I got a whole bunch of warnings.

Dependencies I use:
"dependencies": {
    "core-js": "^3.6.5",
    "express": "4.17.1",
    "imgur": "2.0.0-next.3",
    "lodash": "4.17.21",
    "serve-static": "1.14.1",
    "vue": "^2.6.11",
    "vue-image-upload-resize": "2.3.0",
    "vue-json-pretty": "1.7.1",
    "vue-router": "^3.2.0",
    "vuetify": "^2.4.0",
    "vuex": "^3.4.0"
  },

NodeJS v15.14.0 on MacOS

Can you tell me how to make this work?
Thanks in advance
Frank

**Comment by kaimallea** [comment]
@fsalliau hi, thanks for creating the issue. Neither of those modules are used as dependencies in this project. Can you share more info/output?

![Uploading Screen Shot 2021-04-08 at 1.47.49 PM.png…]()

**Comment by kaimallea** [comment]
<img width="406" alt="Screen Shot 2021-04-08 at 1 59 38 PM" src="https://user-images.githubusercontent.com/228982/114074721-af51cf00-9872-11eb-957b-db56073b1852.png">

**Comment by kaimallea** [comment]
Also, this is a nodejs module -- is your app's configuration currently trying to compile it into your frontend app? That might be the problem

**Comment by fsalliau** [comment]
Thanks for your feedback. I just created a vanilla Vue project using vue cli, without vuex, router or vuetify.
package.json:

  "dependencies": {
    "core-js": "^3.6.5",
    "imgur": "2.0.0-next.3",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },

I've replaced the standard HelloWorld.vue component with:

<template>
  <div>
    <input type="file" @change="handleFileSelect"/>

  </div>
</template>

<script>

import api from '../utils/api.js'

export default {
  name: 'HelloWorld',
  methods: {
    handleFileSelect: function(e){
      api.uploadImage(e.target.files[0]);
    }
  }
}
</script>

and I've added the api.js module as follows:

import { ImgurClient } from 'imgur';

export default {
  uploadImage(f) {
    console.log(f);
  }
}

When running npm run serve, I get the same error on dns and http2 dependency as mentioned in the beginning.
Hope this helps...

KR, Frank

**Comment by kaimallea** [comment]
@fsalliau, I think the issue is that you are trying to use a Node.js module in the browser. This module isn't isomorphic/universal, and is only supported in a Node environment at the moment.

**Comment by kaimallea** [comment]
If you want browser support, you can add a feature request. It is definitely possible with some refactoring.

**Comment by fsalliau** [comment]
@kaimallea yes, I think you're right. No worries, I will handle upload to imgur in backend code. I will close this issue. Thanks for the help!
