### ISSUE TITLE
Expected release date and planned changes for v2

### ISSUE THREAD

**Issue by abdatta** [kaimallea/node-imgur#170]
Hi, pardon me if there's already a doc somewhere mentioning these, but can we know:
- What is the expected release date of stable v2?
- What are the planned features for v2?
- What is done and what is left to do currently in v2?

Thank you

**Comment by KenEucker** [comment]
@abdatta There is not yet a document somewhere outlining the expected release date of `imgur@next`, however there are discussions that you are welcome to participate in here on this repository:
https://github.com/kaimallea/node-imgur/discussions

Specifically, this comment from the maintainer of `node-imgur`, @kaimallea, includes some of the roadmap per se:
https://github.com/kaimallea/node-imgur/discussions/134#discussioncomment-490504

Cheers!
