### ISSUE TITLE
Add factory method as default export for node-imgur v2

### ISSUE THREAD

**Issue by KenEucker** [kaimallea/node-imgur#175]
**Is your feature request related to a problem? Please describe.**
As with other typescript libraries, the default export of this library could be a factory method allowing all different types of configurations between `clientId` and `accessToken` alongside `username` and `password`.

**Describe the solution you'd like**
I want to be able to do the following, in typescript:

```
import imgurClient, { ImgurClient, ImgurConfiguration } from 'imgur'
const imgurClientConfig: ImgurConfiguration = { clientId, username, password } 
const imgurApi: ImgurClient = imgurClient(imgurClientConfig)
```

**Describe alternatives you've considered**

```
import { ImgurClient } from 'imgur'
const imgurApi = new ImgurClient({ clientId })
```

**Comment by cacheflow** [comment]
I like this feature proposal. What are your thoughts @kaimallea?

**Comment by KenEucker** [comment]
you do you, boo!
