### ISSUE TITLE
[BUG] HTTP 400 response status (also tslib dependency is unlisted)

### ISSUE THREAD

**Issue by extremq** [kaimallea/node-imgur#178]
**Describe the bug**
I'm using `imgur@1.0.0` (tried `imgur@next` too) and every time I try uploading an image (tried file and base64, on both versions), I get a Response code 400 (Bad request) error. 
Also, `tslib` is required and I had to install manually it after I installed `imgur@next`.

**To Reproduce**
```js
const imgur = require('imgur');
imgur.setClientId(process.env.IMGUR_ID)
imgur.setAPIUrl('https://api.imgur.com/3/')
```
```js
// banner.data is a base64 string
banner = JSON.parse(req.body.banner)
    imgur.uploadBase64(banner.data).then((json) => {
        console.log(json.link)
    }).catch((err) => {
        console.log(err)
    })
```
```
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (E:\Projects\site\node-shobi\node_modules\imgur\node_modules\got\dist\source\as-promise\index.js:117:42)    
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1619280530987,
    socket: 1619280530995,
    lookup: 1619280531030,
    connect: 1619280531090,
    secureConnect: 1619280531195,
    upload: 1619280531197,
    response: 1619280531721,
    end: 1619280531731,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 8,
      dns: 35,
      tls: 105,
      request: 2,
      firstByte: 524,
      download: 10,
      total: 744
    }
  }
}
```

**Expected behavior**
It should return a 200 response status.

**Environment (please complete the following information):**
 - Library version [e.g. 1.0.0]: 1.0.0
 - OS [e.g. macOS]: Windows 10
 - NodeJS version [e.g.14.16.0]: 14.16.1

**Additional context**
As I said, I also tried it with files, tried it with `@next` and tried multiple function types. It always returned a 400 response status. 
The ID I provided is good, I checked it using [this site](https://playground.btolab.com/sandbox/qa/stackexchange/stackoverflow/17269448/index.php) and it successfully uploaded an image.

**Comment by KenEucker** [comment]
Confirmed, I can reproduce this issue:
![Screen Shot 2021-04-24 at 4 59 18 PM](https://user-images.githubusercontent.com/1720267/115976007-7aa27080-a51e-11eb-96b7-97389a2564b5.png)

(this is not using imgur@next)

**Comment by kaimallea** [comment]
whaa that's cray. Thanks for the report! Looking into this now
