### ISSUE TITLE
Trouble getting album info

### ISSUE THREAD

**Issue by CavemanNinja** [kaimallea/node-imgur#18]
My code, pretty much directly from the example, 

```javascript
var imgur = require('imgur');
var config = require('./config.json');

imgur.setClientId(config.clientid);
console.log('[IMGUR CLIENT ID] ' + imgur.getClientId());

exports.album = function(id) {
	imgur.getAlbumInfo(id)
	    .then(function(json) {
	        console.log(json);
	    })
	    .catch(function (err) {
	        console.error(err.message);
	    });
};
```

my error:
```[TypeError: Object #<Object> has no method 'getAlbumInfo']```

**Comment by CavemanNinja** [comment]
package version 0.1.3 installed through npm seems to be missing getAlbumInfo function.

**Comment by kaimallea** [comment]
Thanks for reporting this! Idk why the files were outdated on NPM, but I bumped the version to 0.1.4 to force it to refresh. I tested and `getAlbumInfo` is there now.
