### ISSUE TITLE
RequestError: Unable to parse location

### ISSUE THREAD

**Issue by Cyanic** [kaimallea/node-imgur#200]
Please excuse me if this is the wrong place, but I tried to follow your instructions and tried to simply upload an image and I'm getting: RequestError: Unable to parse location

I was getting a 417 but now it's just RequestError: Unable to parse location 

Any hints what that error represents?

**Comment by KenEucker** [comment]
@Cyanic, I am sorry that you haven't received a reply. This package is now being maintained in another repository: https://github.com/KenEucker/imgur and the new version might have already addressed your concerns.

imgur@v2 will be released before the end of 2021, and with that will come a couple of breaking changes -> dropping support for filesystem uploads means you have to create your streams on your own and pass them to the API.

Please come help us maintain v2!
