### ISSUE TITLE
[BUG] RequestError The `body` option must be a stream.Readable, string or Buffer

### ISSUE THREAD

**Issue by LIMPIX31** [kaimallea/node-imgur#233]
**Describe the bug**
RequestError The `body` option must be a stream.Readable, string or Buffer

**To Reproduce**
```ts
(await this.imgur.upload(path.join(url))).data.link
url - C:\path\to\image.png
this.imgur - new ImgurClient({ accessToken: this.token });
```

**Expected behavior**
The image will be uploaded to imgur (I specified the token and clientId)

**Environment**
 - Library version 2.0.0-next.6
 - OS Windows 10
 - NodeJS version 16.x.x
- ElectronJS + ReactJS

**Comment by KenEucker** [comment]
@LIMPIX31 filesystem reading has been removed from this package. You will need to create a readableStream using fs yourself and pass that stream to this package.

```
const stream = fs.readFileSync(url)
client.upload(stream)
```

**Comment by LIMPIX31** [comment]
> @LIMPIX31 disregard my previous comment. My apologies.

that is, is this the wrong decision?

**Comment by KenEucker** [comment]
@LIMPIX31 local filesystem uploads should work. If you could provide a repo that demonstrates your issue (sans the accessToken) I could try to assist you.

**Comment by LIMPIX31** [comment]
@KenEucker 
I have a drag'n'drop in which I select a png image, I get its path on my disk, and then do what I described in the problem. I should probably do the upload not in the render thread, since I don't have access to the filesystem in the render thread, it seems unnecessary to me to do the upload to imgur in the main thread, since I can get the Blob/ArrayBuffer/Stream of the image, but ImgurClient#upload does not accept such parameters.

**Comment by LIMPIX31** [comment]
```ts
return (await this.imgur.upload({type: 'base64', image:(await this.blobToBase64(blob))})).data.link
```
The same error. And why does the typescript compiler say data does not exist

**Comment by KenEucker** [comment]
@LIMPIX31 I would suggest breaking up your await statements into individual variables and do some null checking. Either way, if you cannot provide a repo I can't provide much help.

**Comment by LIMPIX31** [comment]
@KenEucker 
```ts
async upload(blob: any): Promise<string> {
    const base64 = await this.blobToBase64(blob) // base64 string of image (AbcDEfg=)
    const response = await this.imgur.upload({type: 'base64', image: base64}) //error here
    // @ts-ignore
    return response.data.link
  }
```
```tsx
<Uploader className={s.uploader} draggable disabledFileItem multiple={false} fileListVisible={false} action={'/'} shouldUpload={file=>{
            app.imgur.upload(file.blobFile).then(link => {
              console.log(link)
            })
            return true
          }}><div>
            <FileUploadIcon/>
          </div></Uploader>
```
`app` is an instance of `Main` class
```ts
export class Main {
  ...
  imgur: Imgur = new Imgur()
  ...
}
```
Imgur class
```ts
import {ImgurClient} from 'imgur';

export class Imgur {
  private readonly token: string = '60f228058d45b9a6a7d594ecec88823ea*******'
  private readonly imgur = new ImgurClient({accessToken: this.token});

  constructor() {

  }

  blobToBase64(blob): Promise<string> {
    return new Promise((resolve, _) => {
      const reader = new FileReader();
      // @ts-ignore
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  }


  async upload(blob: any): Promise<string> {
    const base64 = await this.blobToBase64(blob)
    const response = await this.imgur.upload({type: 'base64', image: base64})
    // @ts-ignore
    return response.data.link
  }

}
```

**Comment by KenEucker** [comment]
> <Uploader className={s.uploader} draggable disabledFileItem multiple={false} fileListVisible={false} action={'/'} shouldUpload={file=>{
            app.imgur.upload(file.blobFile).then(link => {
              console.log(link)
            })
            return true
          }}><div>
            <FileUploadIcon/>
          </div></Uploader>

@LIMPIX31 
This looks like browser code. Are you attempting to use this library in the browser? If so, are you using webpack to compile the library? Currently, this package only works in the node runtime. It is not isomorphic.

(_See: https://github.com/kaimallea/node-imgur/pull/172_)

**Comment by LIMPIX31** [comment]
> > <Uploader className={s.uploader} draggable disabledFileItem multiple={false} fileListVisible={false} action={'/'} shouldUpload={file=>{
> > app.imgur.upload(file.blobFile).then(link => {
> > console.log(link)
> > })
> > return true
> > }}>
> 
> @LIMPIX31 This looks like browser code. Are you attempting to use this library in the browser? If so, are you using webpack to compile the library? Currently, this package only works in the node runtime. It is not isomorphic.
> 
> (_See: #172_)
@KenEucker
It seems that I wrote this in the description of the problem
ElectronJS + ReactJS
Yes I am using webpack. It looks like I have to do the image uploading in the main thread which is executed in NodeJS

**Comment by KenEucker** [comment]
@LIMPIX31 You're welcome to try and use my forked version, which _IS_ an isomorphic build that I am using in both nodejs and the browser: https://github.com/keneucker/node-imgur/tree/release

It is not officially supported by the author of this project, yet.

**Comment by LIMPIX31** [comment]
@KenEucker 
Alas, I was unable to fork due to webpack. I solved the problem by moving the image upload to the main thread, which runs in NodeJS and not the browser
