### ISSUE TITLE
Error: Cannot read property '0' of undefined 

### ISSUE THREAD

**Issue by HuyLe2** [kaimallea/node-imgur#25]
Not sure why i am getting this new error. 
I haven't changed any code and it worked previously. 

Can someone confirm if this package still works?

**Comment by mqchau** [comment]
Hi, I have this error too. Can you please fix it? It is at line lib/imgur.js:152. The res object doesn't have field 'set-cookie'.

This maybe a bug from Imgur too. If so should could you please contact Imgur and explain to them?

Thanks.

**Comment by kaimallea** [comment]
Hey there. Yes, I will take a look at this and get a fix out.

**Comment by kaimallea** [comment]
@HuyLe2 @mqchau hi, can you confirm if this is still an issue? I just tried to reproduce, but I could not. I am uploading single and multiple images from the command-line.

How are you guys uploading images when the issue appears?

**Comment by mqchau** [comment]
Hi @kaimallea , I still see that error. I'm using in my nodejs code to upload images from local hd to imgur. 

Here is the snippets of my code


var imgur = require('imgur');
var config = require('./config');
imgur.setCredentials(config.imgur.username, config.imgur.password, config.imgur.clientid);

// FJwWU is the album name
imgur.uploadFile('/home/quan/image.png', 'FJwWU')
    .then(function(json){
        // show the image link on imgur
        console.log("new link = ", json.data.link);
    }).catch(function(err){
        console.error(err);
    });

**Comment by HuyLe2** [comment]
I think it has something to do with imgur.setCredentails().
If i comment this line out the single file upload works fine.

**Comment by muhammaddadu** [comment]
+1 Experiencing the same issue when invoking another method ```createAlbum()```.
