### ISSUE TITLE
Only have option setCredentials, need one with secret

### ISSUE THREAD

**Issue by ikarius6** [kaimallea/node-imgur#35]
Hi there.

I saw you have setCredentials to store images on a specific account, the problem is I don't want to expose my password on a file, I prefer use the client_secret I got from imgur request access, and I want to know if it is possible use this to store on the specific account.

**Comment by clarkhacks** [comment]
@ikarius6 Imgur has recently updated their API docs! This is great news for you. They have node examples listed as well. If you are wanting to use this module I haven't a clue how to help there.

https://apidocs.imgur.com/

**Comment by KenEucker** [comment]
I believe that #114 addresses this.
