### ISSUE TITLE
Unable to upload image - "Cannot read property 'slice' of undefined"

### ISSUE THREAD

**Issue by s8sachin** [kaimallea/node-imgur#53]
I did this 
```
var imgur = require('imgur');
imgur.setClientId('myClientID');
imgur.setAPIUrl('https://api.imgur.com/3/');
imgur.setCredentials('myEmail', 'MyPassword', 'myClientID');
imgur.uploadUrl('https://octodex.github.com/images/topguntocat.png')
  .then(function (json) {
    console.log(json);
  })
  .catch(function (err) {
    console.error(err);
  });
```
im getting this error.
```
TypeError: Cannot read property 'slice' of undefined
    at /home/sachin/Documents/Private-Dir/sample_proj/node_modules/imgur/lib/imgur.js:177:65
    at _fulfilled (/home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:816:13)
    at /home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:624:44
    at runSingle (/home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:137:13)
    at flush (/home/sachin/Documents/Private-Dir/sample_proj/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Edit: I checked the code in imgur.js. `res.headers.location` is coming undefined
```
var location = res.headers.location;
                var token = JSON.parse('{"' + decodeURI(location.slice(location.indexOf('#') + 1)).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}');
```
Please Help, thanks :)

**Comment by dirtybirdnj** [comment]
+1 for this issue... stuck on the same problem

**Comment by Tonkungs** [comment]
+1 me too

**Comment by dhorrock** [comment]
+1 me too.... anyone have an update or workaround?

**Comment by abhaytalreja** [comment]
+1 for this issue.

**Comment by aferriss** [comment]
+1 me as well

**Comment by lmf-git** [comment]
I think this is still broken

**Comment by VictorioBerra** [comment]
Me too.

**Comment by GustavoBorgesSilva** [comment]
Checking the code i found this, if have an access_token the function  returns "Bearer IMGUR_ACCESS_TOKEN"

If don't, the function goes into the 'else' and arrives into this error

    imgur._getAuthorizationHeader = function () {
        var deferred = Q.defer();
        if (IMGUR_ACCESS_TOKEN) {
            deferred.resolve('Bearer ' + IMGUR_ACCESS_TOKEN); // THIS LINE *************************************
        } else if (IMGUR_USERNAME && IMGUR_PASSWORD) { // ELSE WITH THE ERROR CODE
            var options = {
                uri:      'https://api.imgur.com/oauth2/authorize',
                method:   'GET',
                encoding: 'utf8',
                qs: {

So, to stop the error temporaly, you need to add an ACESS_TOKEN.

To do that y'll need:
1 - Have an app registered in Imgur. If you don't have yet, register follow the steps below.

1.1 - To register an app, enter this link: [https://api.imgur.com/oauth2/addclient](url)

1.2 - Fill in the necessary fields and click "Submit".
  After submitting you will receive the Client-ID.

![image](https://user-images.githubusercontent.com/57686218/101686941-85190d80-3a48-11eb-8ca3-1e26efb2884d.png)

  


2 - Have an ACESS_TOKEN. OBS: that acess_token lasts for about a month. If you don't have yet, register follow the steps below.

 2.1 - To get and ACESS_TOKEN, you need to enter the link below: 

                                                                                
                         Replace the quotation marks BELOW with your Client-ID

https://api.imgur.com/oauth2/authorize?client_id=*************&response_type=token

2.2 - 
You will be redirected to a blank page with the URL containing your ACESS_TOKEN, the URL will look like the one below:

 HERE IS YOUT ACESS_TOKEN, JUST COPY...............HERE V

app.getpostman.com/oauth2/callback#access_token=851160ed76e361527fcac8b6856177479787121b&expires_in=315360000&token_type=bearer&refresh_token=0e81374ef1d0b7b54498a58c5f537284fe839a5d3&account_username=AutobotPublisher&account_id=80856165


Copy from "=" after "acess_token", to "&" before "expires", just the code like this "851160ed76e361527fcac8b6856177479787121b"

///////////////////////////////////////////////////////////////////////

Having the necessary, go to the "imgur.js" folder, located at "/node_modules/imgur/lib/imgur.js".

Right at the beginning of the code you will see these lines: 

    var IMGUR_CLIENT_ID    = process.env.IMGUR_CLIENT_ID || 'f0ea04148a54268';
    var IMGUR_API_URL      = process.env.IMGUR_API_URL || 'https://api.imgur.com/3/';
    var IMGUR_USERNAME     = null;
    var IMGUR_PASSWORD     = null;
    var IMGUR_ACCESS_TOKEN = null;
    var IMGUR_MASHAPE_KEY  = process.env.IMGUR_MASHAPE_KEY;


In the line containing the variable "var IMGUR_ACCESS_TOKEN = null;", replace the value null for your ACESS_TOKEN.


Like this: 

    var IMGUR_ACCESS_TOKEN = '6f4a59d6f356e5e17b788e586c785ac67a2918a6';


Doing so stopped the error from appearing and returns the information normally.

Hope this helps...

**Comment by GustavoBorgesSilva** [comment]
REMEMBERING, AFTER 1 MONTH ACCESS_TOKEN EXPIRES, AND YOU WILL NEED TO REPEAT THE PROCESS OF SENDING THE CLIENT_ID TO THE BLANK PAGE

**Comment by VictorioBerra** [comment]
Honestly its frustrating websites all implement OAuth2 using parts of the spec they like and they ignore other parts. And they have APIs but they never roll libraries to use with them. They have contrived examples on how to do stuff but it always seems to be how to do the 1% case and not the 99% case that most people will want to do.

**Comment by KenEucker** [comment]
@s8sachin I know that this issue was created three years ago, but I ranked to follow up with you and say that this package how supports setting the access token by using the method `setAccessToken`. 

I'm advocating that we close this issue for now and if further issues arise to create a new ticket.

**Comment by FallenUK** [comment]
How would we go about avoiding redoing this manually every 1month. Is there a function in place to use our refresh tokens to generate a new one if its expired ?
