### ISSUE TITLE
`Error: Invalid argument` when use `imgur.getCredits()`

### ISSUE THREAD

**Issue by davidasync** [kaimallea/node-imgur#59]
Hello I got error when trying to use `getCredits` api
Here's my piece of code
```
require('dotenv').load();

const Bluebird = require('bluebird');
const imgur = require('imgur');

imgur.setCredentials(
  process.env.IMGUR_EMAIL,
  process.env.IMGUR_PASSWORD,
  process.env.IMGUR_CLIENT_ID,
);

Bluebird.resolve()
  .then(async () => {
    const res = await imgur.getCredits();
    console.log(JSON.stringify(res, null, 2));
  })
  .catch(console.log)
  .finally(() => console.log('end'));
```

Seems like there's logic error at this code line 47 at `imgur/lib/imgur.js`
```
    if (!operation || typeof operation !== 'string' || ( !payload && operation !== ('credits' && 'search') ) ) {
        deferred.reject(new Error('Invalid argument'));
        return deferred.promise;
    }
```

**Comment by galbenyosef** [comment]
>

> Hello I got error when trying to use `getCredits` api
> Here's my piece of code
> 
> ```
> require('dotenv').load();
> 
> const Bluebird = require('bluebird');
> const imgur = require('imgur');
> 
> imgur.setCredentials(
>   process.env.IMGUR_EMAIL,
>   process.env.IMGUR_PASSWORD,
>   process.env.IMGUR_CLIENT_ID,
> );
> 
> Bluebird.resolve()
>   .then(async () => {
>     const res = await imgur.getCredits();
>     console.log(JSON.stringify(res, null, 2));
>   })
>   .catch(console.log)
>   .finally(() => console.log('end'));
> ```
> 
> Seems like there's logic error at this code line 47 at `imgur/lib/imgur.js`
> 
> ```
>     if (!operation || typeof operation !== 'string' || ( !payload && operation !== ('credits' && 'search') ) ) {
>         deferred.reject(new Error('Invalid argument'));
>         return deferred.promise;
>     }
> ```

Just encountered this also,
try replacing 'line 47' with this one:
 
>   if (!operation || typeof operation !== 'string' || ( !payload && ( (operation !== 'credits') && (operation !== 'search') ) ) ) 

operation !== ('credits' && 'search') is logically wrong.

**Comment by KenEucker** [comment]
@kaimallea the logic referenced in the comment above does seem incorrect:
https://github.com/kaimallea/node-imgur/blob/main/lib/imgur.js#L49

```
(!payload && operation !== ('credits' && 'search'))
```

Should change to something like this:

```
(!(operation && payload) || (['credits',search'].indexOf(operation) !== -1)) {
```
