### ISSUE TITLE
Implement image actions

### ISSUE THREAD

**Issue by kaimallea** [kaimallea/node-imgur#66]
- [ ] Return info about a specific image
- [ ] Upload one or more image(s) w/ globbing (also fix #50)
- [x] Delete an image
- [ ] Update image information
- [ ] Favorite an image
- [ ] Get Image Count

**Comment by cacheflow** [comment]
I'll take this.

**Comment by cacheflow** [comment]
Working on delete right now. Just need to write some tests for it.

**Comment by kaimallea** [comment]
🙌

**Comment by KenEucker** [comment]
What's the status on update and can I contribute?

**Comment by cacheflow** [comment]
Sure go ahead. @KenEucker. I have a few PRs already for favoriting, image count retrieval, and caching.  I don't think anyone has done globbing yet. https://github.com/kaimallea/node-imgur/pulls/cacheflow

**Comment by KenEucker** [comment]
@kaimallea would there be a chance for an update on this package? Given the PRs already waiting, and the time between releases, maybe we could give this package some attention?
