### ISSUE TITLE
self._form.getHeaders is not a function

### ISSUE THREAD

**Issue by mittalyashu** [kaimallea/node-imgur#70]
I am getting this error when the imgur code is executed.

```js
imgur
	.uploadFile(event.target.files[0].path)
	.then(data => {
		console.log(data);
	})
	.catch(err => {
		console.log(err);
	});
```

### Screenshots

![image](https://user-images.githubusercontent.com/29014463/58759141-ec482e80-8542-11e9-959b-92216c658daa.png)

**Comment by kaimallea** [comment]
this should be resolved in both `imgur@1.x` and `imgur@next`
