### ISSUE TITLE
Updating an image?

### ISSUE THREAD

**Issue by wesboyt** [kaimallea/node-imgur#71]
Is it possible to update an image or perhaps remove it and replace it at the same url?
only thing kinda similar seems to be using an album and removing/adding images but they wouldnt have the same url

**Comment by KenEucker** [comment]
@wesboyt I looked through the documentation and I do not think that this is possible. 

Relevant:
https://apidocs.imgur.com/#de179b6a-3eda-4406-a8d7-1fb06c17cb9c

With this in mind, this ticket should be closed.
