### ISSUE TITLE
Package is now unusable, request is deprecated.

### ISSUE THREAD

**Issue by KenEucker** [kaimallea/node-imgur#99]
Request has been deprecated and can no longer be installed from npm. With this, the node-imgur package (or "imgur" on npm) is unusable.

This package needs to be updated. I'm currently working with the javascript version (not the TS version) and replacing request with got. I would be happy to collaborate with others to update this package and maintain it moving forward.

**Comment by laxuscullen** [comment]
Is there any update on this? The issue is opened for 6 days and no one has even acknowledged it.

**Comment by KenEucker** [comment]
@laxuscullen 

Unfortunately, over the last several months, I have not been able to get the maintainer of this project to respond to any issues or PRs created for this project. The account @kaimallea is active here on GitHub but they either don't see these messages or they don't have an interest in further maintaining this project. Given the amount of stale PRs and unaddressed issues, it seems that they've given up.

It's not only unfortunate, it's frustrating. This package's name is "imgur" under npm. It gets thousands of downloads a week.

**Comment by kaimallea** [comment]
@KenEucker @laxuscullen Hi, thanks for reaching out. Unfortunately I am not able to commit to actively maintaining this repo at this time, but I would be up for transferring ownership if that's something of interest (cc @cacheflow who has contributed in the past).

I've also considered transferring the "imgur" npm name to Imgur the company, but that won't solve your problem of having an active maintained package, as I don't believe they have an official one.

Have you considered forking? I'm happy to update readme/docs to mention inactivity and folks should now use your active maintained fork.

I'm also open to other suggestions.

**Comment by kaimallea** [comment]
Also I can roll `master` back to match the last npm release, so in the mean time I can at least accept patches.

**Comment by kaimallea** [comment]
Alright, `master` is now reset to what it was for the last release, `v0.3.1`

**Comment by KenEucker** [comment]
@kaimallea,

I want to thank you so much for your time here. I understand that this project is in your rear view mirror a little bit but I want you to know that I appreciate that I have been able to use it in my own FOSS projects.

I would be open to a transfer and/or collaboration with others, including @cacheflow. I would be new to contributing to this project so I would defer to whatever the previous collaborators thought was best, if they have such an interest. I do have an interest in seeing this package continue and I have already begun to improve on v0.3.1. Given the amount of PR's already available, I am also willing to go through the testing and merging those changes in as it makes sense.

Thank you for rolling back the default branch to the latest npm release. I have already forked the repository and I will continue to watch this thread and other issues for any consensus that may arise.

Thank you for contributing to the FOSS community!

**Comment by kaimallea** [comment]
@KenEucker I appreciate you, thanks again for reaching out. It will be evident once you view source that this was written long ago. There are some obvious things that can be rewritten/removed/updated to align with modern-day NodeJS. With that said, I'm completely open to suggestions.

But maybe the immediate fix is swapping out `request`, then after doing an overhaul.

**Comment by KenEucker** [comment]
That's my plan!

Replace `request` first (v0.3.2 or 0.4.0?) and then focusing on a good update given the issues on this repository. Let me know if you want to do any transferring sooner rather than later. Otherwise, I will check back in with you once I have `request` removed.

**Comment by KenEucker** [comment]
This was addressed in #101
